<?php

/**
 * @file
 * Contains seller_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function seller_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the seller_registration module.
    case 'help.page.seller_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Seller Registration module') . '</p>';
      return $output;

    default:
  }
}
